services:
  db:
    image: mysql:8
    container_name: demo_db
    environment:
      MYSQL_DATABASE: demo_ci
      MYSQL_USER: app
      MYSQL_PASSWORD: app1234
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: demo_backend
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: demo_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  qa:
    build: ./qa
    container_name: demo_qa
    depends_on:
      - frontend:
          condition: service_started
    volumes:
      - ./playwright-report:/app/playwright-report
